package.json, src/coin/baseCoin/coin.ts, src/coin/trx/network/coin.ts, src/coin/trx/transaction.ts, src/transaction.ts, src/transactionBuilder.ts, test/resources/testCoin.ts, test/resources/testTransaction.ts, test/unit/coin/trx/trx.ts, test/unit/transactionBuilder.ts
The address in the signing step is redundant. At the signing step, we should already have all the information needed in the transaction to verify it is valid.
This check can easily be replaced by deriving the public key and subsequent addresses from the private key anyway.
=> TRON-82 - Remove address param from builder.sign()

src/coin/baseCoin/coin.ts, src/coin/baseCoin/errors.ts, src/coin/trx/network/coin.ts, src/coin/trx/transaction.ts, src/coin/trx/utils.ts, src/transactionBuilder.ts, test/resources/testCoin.ts, test/unit/coin/trx/trx.ts, test/unit/transactionBuilder.ts
The function deserializes tx hex, updates the expiration date, and
reserializes the tx hex.
I was able to send a successful extended multisig transaction using this code in coins-sandbox:
```
... normal send stuff
const future_date_amount_ms = 4000;
tx.raw_data.expiration = tx.raw_data.expiration += future_date_amount_ms;
const updatedTxHex = bitgoAccountLib.Trx.Utils.extendTransaction(tx.raw_data_hex, future_date_amount_ms);
tx.raw_data_hex = updatedTxHex; 
tx.txID = calculateTxid(tx);
... signature, signature, send
```
=> [TRON-81] Add utility to future date Tron transactions

package.json
Turns out we need `protobufjs` as a main dependency.
Bumping the version number to prepare us for a new alpha release
=> Udpate version and fix dev dependency

src/coin/trx/iface.ts, src/coin/trx/keyPair.ts, src/utils/crypto.ts, test/unit/coin/trx/keyPair.ts, test/unit/coin/trx/trx.ts, test/unit/utils/crypto.ts
There are no "compressed" private keys. A more apt terminology for a
hex-encoded private key (the `d` value) would be the `raw`
private key.
This is in preparation of removing the dependency on `bitgo-utxo-lib`.
=> Fix terminology of raw private keys

src/coin/baseCoin/baseTransaction.ts, src/coin/baseCoin/iface.ts, src/coin/trx/transaction.ts, src/coin/trx/transactionBuilder.ts, src/index.ts, test/unit/coin/trx/transaction.ts, test/unit/coin/trx/transactionBuilder.ts
Destination and sender is not a good name. Inputs and outputs are easier to understand. It also makes it easier to consume by library users.
=> Use inputs and outputs nomenclature

src/coin/trx/keyPair.ts, src/coin/trx/utils.ts, test/unit/coin/trx/keyPair.ts, test/unit/coin/trx/util.ts
[XTZ-29](https://bitgoinc.atlassian.net/browse/XTZ-29) Add methods to sign and verify random string messages using the current Key Pair.
This is used to prove that a sender has control over the private keys.
=> Add sign and verify message functions

src/coin/baseCoin/errors.ts, src/coin/trx/transactionBuilder.ts, test/resources/trx.ts, test/unit/coin/trx/transactionBuilder.ts
Fixes #37 
As specified, `validateTransaction()` verifies a Tron transaction has the right transaction id, per the [Tron spec](https://github.com/tronprotocol/documentation/blob/master/TRX/Tron-overview.md). Introduced the crypto library from standard lib.
Unit tests included.
=> Validate transaction implementation

src/coin/xtz/iface.ts, src/coin/xtz/keyPair.ts, src/coin/xtz/utils.ts, test/unit/coin/xtz/keyPair.ts, test/unit/coin/xtz/util.ts
Add validation for address, block and transaction hashes
Validate encoding, prefix and length
In Tezos, hashes are encoded using Base58Check
Ticket: BG-17820
=> Implement hash validation for Tezos

CODEOWNERS
[BG-17475](https://bitgoinc.atlassian.net/browse/BG-17475) Luis is the main reviewer for Tezos development. Adding him as CODEOWNER
=> Add Luis as CODEOWNER

package.json, src/coin/trx/transactionBuilder.ts, test/resources/testTransactionBuilder.ts
Update MAJOR version, since the transactionBuilder’s build() method is now async.
See: https://github.com/BitGo/bitgo-account-lib/pull/54/files#diff-4e77c7638c5579df1efa8d2624cd3480R65
Ticket: BG-18616
=> Bump package version

src/coin/xtz/multisigUtils.ts, src/coin/xtz/transactionBuilder.ts, test/unit/coin/xtz/offlineTransactionBuilder.ts
When signing a Tezos half signed transaction, the account lib generates a new array of signatures to replaces the existing one. Old signatures are discarded while they should be merged if any exist.
TICKET: BG-19070
=> Fix signature override

src/coin/xtz/iface.ts, src/coin/xtz/multisigUtils.ts, src/coin/xtz/transactionBuilder.ts, test/unit/coin/xtz/offlineTransactionBuilder.ts
If the signature index is not provided, search for the first nullified signature and replace it.
This makes the order of the sign operations implicit.
TICKET: BG-17090
=> Make sign order optional

package-lock.json, package.json, src/coin/xtz/utils.ts, test/unit/coin/xtz/util.ts
Use [elliptic](https://www.npmjs.com/package/elliptic) to verify the signatures produced by our library.
The decoding operations are based on:
- https://github.com/ecadlabs/taquito/blob/5dc2dee9d6d51430afbccee4c0b6f356de840240/packages/taquito-signer/src/taquito-signer.ts#L74
- https://github.com/ecadlabs/taquito/blob/5dc2dee9d6d51430afbccee4c0b6f356de840240/packages/taquito-signer/src/ec-key.ts#L72
=> Add signature verification for Tezos

src/coin/xtz/transactionBuilder.ts, test/unit/coin/xtz/transactionBuilder.ts
We currently only take Tezos public keys as valid ones when revealing an account, but we should take any other format the `KeyPair` class supports, including xpubs.
TICKET: BG-19342
=> Allow xpubs as a valid arguments when revealing public keys

src/coin/xtz/multisigUtils.ts, src/coin/xtz/transaction.ts, test/unit/coin/xtz/offlineTransactionBuilder.ts, test/unit/coin/xtz/transactionBuilder.ts
In this PR:
* Add a method to get the signatures and indexes from a multisig transfers (Solves https://github.com/BitGo/bitgo-account-lib/issues/80).
* Add a method to get the indexes of different operations. This is used to inspect the transaction and properly sign.
=> Add methods to work with nested signatures

src/coin/eth/keyPair.ts, src/coin/eth/transaction.ts, src/coin/eth/transactionBuilder.ts, src/coin/eth/utils.ts, test/unit/coin/eth/keyPair.ts, test/unit/coin/eth/transactionBuilder.ts
The transactionbuilder and keypair for ETH were broken with the
following bugs:
- keypair would not generate addresses from an extended key, simply due
to not handling the case
- transactionbuilder would throw if not given a counter, even though
there is a default
This commit fixes the above issues and adds some tests
Ticket: BG-20990
=> Fix Transactionbuilder and keypair

.drone.yml
Previously it was possible to merge code that passed unit tests but did
not build correctly, as tsc has stricter rules than ts-node. This commit
adds a step to the build pipeline that checks to ensure that the code
actually compiles with `npm run build`.
Ticket: BG-21163
=> Add Build step to drone yaml

CODEOWNERS
I am reviewing a lot of code in this repository, and it would be helpful
to be able to merge code without requiring another codeowner.
Ticket: BG-21216
=> Add Mark Toda as codeowner

src/coin/cgld/types.ts, test/unit/coin/cgld/transactionBuilder.ts
Celo coins treats 0 value ('0x0' in hex format) as empty ('0x'). This commit adds a sanitizer to the celoTransaction class
=> BGA-118 sanitiza hex values

src/coin/eth/utils.ts, test/unit/coin/eth/transactionBuilder.ts
The transaction builder would fail when deserializing transactions that
started with a 0-prefixed address, because ethereumjs-abi is dumb and
loses that prefix padding when deserializing for some reason. This
commit pads addresses with 0s until they reach the desired 20 byte
length
Ticket: BG-21435
=> Fix 0-prefixed addresses

src/coin/eth/types.ts
The ETH transaction builder was very slow for wallet initialization
transactions because we were parsing data (which can be huge) using
BigNumber, which is slower the bigger the number gets. In fact, we could
keep the data parsing logic very simple here as we just need the hex
string.
Ticket: BG-21437
=> Improve transaction builder speed

package-lock.json, package.json
This commit bumps the account-lib version to 1.3.0 to include new
changes including CELO wallet token sending
Ticket: BG-21720
=> Bump version to 1.3.0

src/coin/eth/enum.ts, src/coin/eth/iface.ts, src/coin/eth/transaction.ts, src/coin/eth/transferBuilder.ts, src/coin/eth/utils.ts, test/unit/coin/cgld/transactionBuilder/send.ts, test/unit/coin/eth/transactionBuilder/send.ts
This commit adds the inputs, outputs, and signatures fields for send
transactions. It parses the transaction data to get these fields, and
exposes them through the same interface that other coins use. This will
help dependent libraries to properly decode transactions and understand
what is happening
Ticket: BG-22118
=> Parse inputs, outputs and signatures for transactions

package-lock.json, package.json
This commit bumps the Bitgo-account-lib version to v1.5.0 to include new
fixes for CGLD
Ticket: BG-22185
=> Bump version to 1.5.0

package-lock.json, package.json
This commit bumps bitgo-account-lib to 1.6.0 to include
Ticket: BG-22229
=> Bump to 1.5.1

package-lock.json, package.json
This commit bumps bitgo-account-lib to v1.6.0, including some new
changes and fixes
Ticket: BG-22366
=> Bump to 1.6.0

package-lock.json, package.json
This commit bumps bitgo-account-lib package to 1.7.0 to include new
features and fixes
Ticket: BG-22445
=> Bump to 1.7.0

src/coin/trx/keyPair.ts, src/coin/trx/transaction.ts, src/coin/trx/transactionBuilder.ts, src/coin/xtz/keyPair.ts
Using `import * as crypto from 'crypto';` imports all fields from the
'crypto' library into the current scope. This includes some deprecated
fields which emit a DeprecationWarning to stdout when the field is
imported, including when using import star. This is discoverable when
running node with the --trace-warnings flag when these warnings are
emitted.
Instead, just import the field desired. This should prevent the
deprecated field from being imported.
Ticket: BG-22502
=> Fix crypto deprecation warnings caused by __importStar

package-lock.json, package.json
This commit bumps the package version to include a fix for celo signing
Ticket: BG-22735
=> Bump account lib to 2.0.0-rc.1
