- package-lock.json
- src/index.ts
- src/protobuf/Contract_pb.js
- test/unit/index.ts
The explain transaction function needs information about the transaction timestamp and expiration, and we need to add a helper function within index.ts for them.
> TRON-71 Add Helper Function to Account Lib 

- package.json
- src/coin/baseCoin.ts
- src/coin/test/index.ts
- src/coin/trx/index.ts
- src/index.ts
- src/transactionBuilder.ts
- test/transactionBuilder.ts
This is part of TRON-39. The purpose of this series of commits is to create scaffolding for account-lib's transactionBuilder. The final goal will be base tests, along with Tron as a mock (just stubbed out for now)
> TRON-39 - create account lib scaffolding

- src/coin/baseCoin/coin.ts
- src/coin/baseCoin/index.ts
- src/index.ts
Left out some default exports, so blocking BitGoJS implementation.
> TRON-39 - Default exports for baseCoin

- package.json
Setting the right name for bitgo account lib
> TRON-39 - Initial version of bitgo-account-lib for release

- package.json
https://bitgoinc.atlassian.net/browse/TRON-82
> Update coverage config to only measure src/

- package-lock.json
- package.json
- src/coin/trx/iface.ts
- src/coin/trx/utils.ts
- test/unit/coin/trx/util.ts
[TRON-133](https://bitgoinc.atlassian.net/browse/TRON-133) Use bitcoin account generation methods instead of Tron Web ones.
> TRON-133 use bitcoin key generation libs

- package-lock.json
- package.json
> NPM audit fix for node 10

- DEVELOPER.md
- README.md
- resources/README.md
This is a fairly major refactor to the project `README`, `DEVELOPER.md` (contribution guide),
and `resources/README` files for improved readability and context for any external developer new to the project.
The goal is to get this project ready for contributions from developers outside of BitGo. In order to achieve that, much more context was needed in order for newcomers to orient themselves with regards to the project.
Addresses #29
> Refactor Documentation - Prep the project for external contributions

- package-lock.json
- src/coin/baseCoin/enum.ts
- src/coin/baseCoin/errors.ts
- src/coin/baseCoin/iface.ts
- src/coin/trx/iface.ts
- src/coin/trx/index.ts
- src/coin/trx/key.ts
- src/coin/trx/keyPair.ts
- src/coin/trx/signature.ts
- src/coin/trx/transactionBuilder.ts
- src/coin/trx/utils.ts
- src/utils/crypto.ts
- test/resources/trx.ts
- test/unit/coin/trx/keyPair.ts
- test/unit/coin/trx/trx.ts
- test/unit/coin/trx/util.ts
- test/unit/utils/crypto.ts
- types/bitgo-utxo-lib/index.d.ts
[BLOCK-170](https://bitgoinc.atlassian.net/browse/BLOCK-170) It should be possible to sign a Tron transactions using xprvs as well as adding destinations using xpubs.
It should be possible to sign with an xprv or with the original prv used by the protocol. In Tron, this is a compressed private key.
> Implement KeyPair class

- package-lock.json
- package.json
- src/coin/xtz/address.ts
- src/coin/xtz/iface.ts
- src/coin/xtz/index.ts
- src/coin/xtz/keyPair.ts
- src/coin/xtz/utils.ts
- src/index.ts
- test/unit/coin/xtz/keyPair.ts
[BG-17474](https://bitgoinc.atlassian.net/browse/BG-17474) Add Tezos key pair management logic.
> BG-17474 Initial Tezos KeyPair code

- src/coin/xtz/index.ts
> Expose Tezos interfaces and utils functions

- package.json
- resources/README.md
- resources/xtz/multisig.ts
- src/coin/baseCoin/baseTransaction.ts
- src/coin/baseCoin/baseTransactionBuilder.ts
- src/coin/trx/transaction.ts
- src/coin/trx/transactionBuilder.ts
- src/index.ts
- test/resources/testTransaction.ts
[BG-17815](https://bitgoinc.atlassian.net/browse/BG-17815) First PR cleaning up some code documentation and adding Tezos multisig contract.
It also closes https://github.com/BitGo/bitgo-account-lib/issues/28
> BG-17815 Add Tezos resources and clean up docs

- package-lock.json
- package.json
- src/coin/baseCoin/baseTransaction.ts
- src/coin/baseCoin/iface.ts
- src/coin/trx/index.ts
- src/coin/xtz/iface.ts
- src/coin/xtz/index.ts
- src/coin/xtz/transaction.ts
- src/coin/xtz/utils.ts
- test/resources/xtz/xtz.ts
- test/unit/coin/xtz/transaction.ts
[BG-17815](https://bitgoinc.atlassian.net/browse/BG-17815) Add Tezos transaction model supporting:
* Wallet initialization transaction creation
* Transaction signing
> Add Tezos transaction object

- src/coin/baseCoin/baseTransaction.ts
- src/coin/baseCoin/errors.ts
- src/coin/trx/transactionBuilder.ts
- test/resources/trx.ts
- test/unit/coin/trx/transactionBuilder.ts
Closes #36 
Adding methodology for validation check for a raw transaction
> Validate trx

- package-lock.json
- src/coin/baseCoin/baseTransaction.ts
- src/coin/trx/transactionBuilder.ts
- src/coin/trx/utils.ts
- src/coin/xtz/keyPair.ts
- src/coin/xtz/transactionBuilder.ts
- src/coin/xtz/utils.ts
- test/unit/coin/baseCoin/transactionBuilder.ts
- test/unit/coin/trx/keyPair.ts
- test/unit/coin/trx/transaction.ts
- test/unit/coin/trx/transactionBuilder.ts
- test/unit/coin/trx/util.ts
- test/unit/coin/xtz/keyPair.ts
- test/unit/coin/xtz/transaction.ts
- test/unit/coin/xtz/transactionBuilder.ts
- test/unit/coin/xtz/util.ts
- test/unit/index.ts
- test/unit/utils/crypto.ts
- tsconfig.json
Change module imports
Move class member initialization to controllers
Cleanup by eslint
Ticket: BG-18455
> Fix compatibility issues with Babel

- resources/xtz/multisig.ts
- src/coin/trx/transactionBuilder.ts
- src/coin/xtz/utils.ts
Add contract counter parameter to the generated data to sign (`genericMultisigDataToSign `)
> BG-18444 Fix multisig send

- package-lock.json
- package.json
Use the same version of blake2b for compatibility with bitgo-utxo-lib and the SDK
Ticket: BG-18644
> Use BitGo/blake2b in account-lib

- resources/xtz/multisig.ts
- src/coin/xtz/transactionBuilder.ts
- test/unit/coin/xtz/transactionBuilder.ts
[BG-18444](https://bitgoinc.atlassian.net/browse/BG-18444) Add empty fields for missing signatures in the transfer script.
> BG-18444 Add empty extra signatures until m

- package-lock.json
- resources/xtz/multisig.ts
- src/coin/xtz/iface.ts
- src/coin/xtz/transaction.ts
- src/coin/xtz/transactionBuilder.ts
- src/coin/xtz/transferBuilder.ts
- src/coin/xtz/utils.ts
- test/unit/coin/xtz/offlineTransactionBuilder.ts
- test/unit/coin/xtz/transactionBuilder.ts
- test/unit/coin/xtz/transferBuilder.ts
Add methods to produce a unsigned serialized transaction and to sign it in an offline environment
> BG-18418 Fix offline signing

- package-lock.json
- package.json
- src/coin/xtz/multisigUtils.ts
- src/coin/xtz/transaction.ts
- src/coin/xtz/transactionBuilder.ts
- src/coin/xtz/utils.ts
Microservices build fails due to multisig.ts file in the dist folder
Ticket: BG-19082
> Fix build for use with SDK

- package-lock.json
- package.json
Update version of minimist dependency in package-lock.json manually
Ticket: BG-19090
> Fix account-lib's vulnerable dependencies

- package-lock.json
- package.json
Update account-lib version to 1.0.2
> BG-17966 Update version

- src/coin/xtz/iface.ts
- src/coin/xtz/multisigUtils.ts
- src/coin/xtz/transaction.ts
- src/coin/xtz/transactionBuilder.ts
- test/unit/coin/xtz/transaction.ts
- test/unit/coin/xtz/transactionBuilder.ts
Add an option to delegate from the wallet contract on it's origination.
> BG-19786 Delegate on wallet creation

- src/coin/xtz/index.ts
- src/coin/xtz/utils.ts
Implement isValidPrivateKey
Validate xpubs in isValidPublicKey
Export multisigUtils as part of Utils for XTZ
Ticket: BG-18979
> Export XTZ util functions from account-lib

- package-lock.json
> Update package-lock.json for new version 1.1.0

- package.json
- src/coin/trx/transactionBuilder.ts
- src/coin/xtz/utils.ts
A bundle of small changes:
- Update package.json
- Change != to !==
- Remove `this` when referring to hashTypes since it breaks when transpiled to javascript
> Minor fixes

- src/coin/eth/utils.ts
- test/unit/coin/eth/transactionBuilder.ts
- test/unit/coin/eth/utils.ts
> Fixed the forwarder address initialization

- package-lock.json
- package.json
Changes included:
* Added support for eth, added mapping from rsk to eth
* Add validations in ETH transaction builder
* Celo Wallet initialization
* Fix Transactionbuilder and keypair for ETH
* Simplify ETH Transaction
* Minor fixes
* Add Build step to drone yaml
* Implement Tezos forwarder contract
* ETH forwarder deploy
* Fix Wallet Creation Bugs
* Sanitize hex values for Celo
* Celo transfer transaction from serialized
* Fix 0-prefixed addresses for ETH
* Improve ETH transaction builder speed
Ticket: BG-21498
> Bump account-lib version for release 1.2.0

- src/coin/xtz/multisigUtils.ts
- src/coin/xtz/transaction.ts
- test/unit/coin/xtz/transactionBuilder.ts
Add a method to extract the owners in a multisig wallet origincation transaction.
TICKET: BG-20411
> BG-20411 Get owners from origination

- src/coin/cgld/utils.ts
Solving Sonar major issues by removing unused constants.
> Remove unused constants in Celo deserialization

- src/coin/eth/transactionBuilder.ts
- test/unit/coin/cgld/transactionBuilder/addressInitialization.ts
- test/unit/coin/cgld/transactionBuilder/send.ts
- test/unit/coin/cgld/transactionBuilder/staking.ts
- test/unit/coin/cgld/transactionBuilder/walletInitialization.ts
- test/unit/coin/etc/transactionBuilder.ts
- test/unit/coin/eth/transactionBuilder/addressInitialization.ts
- test/unit/coin/eth/transactionBuilder/send.ts
- test/unit/coin/eth/transactionBuilder/walletInitialization.ts
- test/unit/coin/rbtc/transactionBuilder.ts
We removed the source because we can get it from the signature
> BGA-165 Remove source

- src/coin/cgld/stakingBuilder.ts
- src/coin/cgld/types.ts
- src/coin/eth/transactionBuilder.ts
- src/coin/eth/utils.ts
Solved the following issues
src/coin/cgld/stakingBuilder.ts
Function has a complexity of 11 which is greater than 10 authorized
src/coin/cgld/types.ts
Function has a complexity of 13 which is greater than 10 authorized.
src/coin/eth/transactionBuilder.ts
Function has a complexity of 15 which is greater than 10 authorized.
src/coin/eth/utils.ts
Function has a complexity of 11 which is greater than 10 authorized.
> BGA-149 Sonar issues

- .codecov.yml
- .drone.yml
- .gitignore
The underlying image has been changed, a token was regenerated by danny 
and this adds a codecov yaml file.
Ticket: BG-22409
> Re-enable code coverage by changing the image

- package-lock.json
- package.json
- src/coin/xtz/multisigUtils.ts
Fix storage field of origination operation script to match value from
deployForwarderContract script in coins-sandbox
Ticket: BG-22480
> Fix XTZ forwarder contract deployment tx

- src/coin/baseCoin/baseKeyPair.ts
- src/coin/baseCoin/ed25519KeyPair.ts
- src/coin/baseCoin/errors.ts
- src/coin/baseCoin/secp256k1ExtendedKeyPair.ts
- src/coin/eth/keyPair.ts
- src/coin/trx/keyPair.ts
- src/coin/xtz/keyPair.ts
From stellar seed still TBD
Ticket: BG-22623
> Splitting keypair class into secp and ed based keycurves

- package-lock.json
- package.json
Changing CGLD to CELO and adding ability to flush tokens
Ticket: BG-22685
> Bump version to 2.0.0-rc.0
